### ISSUE TITLE
apollo-router release assets were renamed in release 0.16.0

### ISSUE THREAD

**Issue by garypen** [safx/asdf-apollo-router#1]
**Describe the bug**

The download paths for the release assets changed when the PR to fix this issue merged: https://github.com/apollographql/router/issues/1385

**Steps to reproduce**

```
% asdf install apollo-router 1.0.0
* Downloading apollo-router release 1.0.0...
curl: (22) The requested URL returned error: 404
asdf-apollo-router: Could not download https://github.com/apollographql/router/releases/download/v1.0.0/router-1.0.0-x86_64-macos.tar.gz
%
 ```

**Expected behavior**

`apollo-router` downloads and installs

**Screenshots**

N/A

**Additional context**

The changes were:

 linux is at `https://rover.apollo.dev/tar/router/x86_64-unknown-linux-gnu/v1.0.0`
 macos is at ` https://rover.apollo.dev/tar/router/x86_64-apple-darwin/v1.0.0`
 windows is at` https://rover.apollo.dev/tar/router/x86_64-pc-windows-msvc/v1.0.0`

**Comment by safx** [comment]
I've fixed it. Please try the latest version with ` asdf plugin update apollo-router`. Thank you for your reporting!
